//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwachhBharatAPI.Dal.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class SauchalayAddress
    {
        public int Id { get; set; }
        public string SauchalayID { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Lat { get; set; }
        public string Long { get; set; }
        public string Name { get; set; }
        public string ImageUrl { get; set; }
        public string QrImageUrl { get; set; }
        public string Mobile { get; set; }
        public string Tot { get; set; }
        public Nullable<int> Tns { get; set; }
        public string SauchalayQRCode { get; set; }
        public string ReferanceId { get; set; }
        public Nullable<System.DateTime> lastModifiedDate { get; set; }
        public Nullable<int> AreaId { get; set; }
        public Nullable<int> ZoneId { get; set; }
        public Nullable<int> WardNo { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<System.DateTime> lastModifiedDateEntry { get; set; }
        public string TOEMC { get; set; }
        public string TOC { get; set; }
        public string QRCodeImage { get; set; }
        public Nullable<bool> QRStatus { get; set; }
        public Nullable<System.DateTime> QRStatusDate { get; set; }
        public byte[] BinaryQrCodeImage { get; set; }
        public Nullable<int> PrabhagId { get; set; }
    }
}
